/**
 * HVAC Landing Page Template
 * Content is injected at build time via VITE_ environment variables
 * or a content.json file generated by site_generator.py.
 *
 * Variables expected (set by site_generator.py before `npm run build`):
 *   VITE_BUSINESS_NAME, VITE_HEADLINE, VITE_SUBHEADLINE,
 *   VITE_SERVICES (JSON array), VITE_PHONE, VITE_CTA_TEXT
 */

const content = {
  businessName: import.meta.env.VITE_BUSINESS_NAME || "Your HVAC Company",
  headline:     import.meta.env.VITE_HEADLINE      || "Fast, Reliable HVAC Service",
  subheadline:  import.meta.env.VITE_SUBHEADLINE   || "Serving the local community for over 20 years.",
  services:     JSON.parse(import.meta.env.VITE_SERVICES || '["AC Repair","Heating","Maintenance Plans"]'),
  phone:        import.meta.env.VITE_PHONE         || "(555) 000-0000",
  ctaText:      import.meta.env.VITE_CTA_TEXT      || "Get a Free Quote",
};

export default function App() {
  return (
    <div style={{ fontFamily: "sans-serif", maxWidth: 800, margin: "0 auto", padding: "2rem" }}>
      <header>
        <h1>{content.businessName}</h1>
      </header>

      <section>
        <h2>{content.headline}</h2>
        <p>{content.subheadline}</p>
        <a href={`tel:${content.phone}`} style={{ fontSize: "1.5rem", fontWeight: "bold" }}>
          {content.phone}
        </a>
      </section>

      <section>
        <h3>Our Services</h3>
        <ul>
          {content.services.map((s) => <li key={s}>{s}</li>)}
        </ul>
      </section>

      <section>
        <a href="#contact" style={{ background: "#e63946", color: "#fff", padding: "1rem 2rem", borderRadius: 4, textDecoration: "none" }}>
          {content.ctaText}
        </a>
      </section>
    </div>
  );
}
