"""
Site Generator Agent
Uses a React template (templates/hvac/) as a base and populates it with
business-specific content generated by Claude, then deploys to Vercel.
"""

import anthropic


def generate_content(lead: dict, client: anthropic.Anthropic) -> dict:
    """
    Ask Claude to produce copy for: headline, subheadline, services list,
    about blurb, and CTA text — all tailored to the specific business.
    Returns a dict matching the template's content schema.
    """
    # TODO: implement
    raise NotImplementedError


def build_site(lead: dict, content: dict, template_dir: str) -> str:
    """
    Inject generated content into the React template and return the
    path to the built output directory.
    """
    # TODO: run npm build with injected env vars / JSON payload
    raise NotImplementedError


def deploy_to_vercel(build_dir: str, token: str) -> str:
    """Deploy the built site to Vercel and return the preview URL."""
    # TODO: call Vercel CLI or REST API
    raise NotImplementedError


def run(lead_ids: list[int] | None = None):
    """Entry point called by the pipeline orchestrator."""
    raise NotImplementedError
